version: '3.8'
services:
  db:
    image: postgres:13.0-alpine

    volumes:
      - db_value:/var/lib/postgresql/data/

    env_file:
      - ./.env

  backend:
    image: lyganin/foodgram_backend:latest
    # build: .
    restart: always
    volumes:
      - static_backend_value:/app/static_backend/
      - media_value:/app/media/              #AVC
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: lyganin/foodgram_frontend:latest
    # build: .
    # restart: always
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - static_backend_value:/var/html/static_backend/     #AVC
      - media_value:/var/html/media/               #AVC
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml     #AVC
    depends_on:
      - backend
      - frontend  

volumes:
  db_value:
  result_build:
  static_backend_value:
  media_value:
