# Generated by Django 3.2.19 on 2023-05-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во ингредиента'),
            preserve_default=False,
        ),
    ]
